### ISSUE TITLE
Add column not updating cached metadata

### ISSUE THREAD

**Issue by steinkel** [cakephp/migrations#199] opened 2016-02-24 20:19 UTC
I have the following migration 

        // add book_id to chapters
        $chapters = $this->table('chapters');
        $chapters
            ->addColumn('chapter_book_id', 'integer', array('null' => true))
            ->save();

And later on I was manually updating the chapter_book_id field in another migration, but the field was not saved in database. After some time debugging, the cached metadata was not updated and the field was not recognized as part of the table, so the save operation was updating the value in DB.

I've manually fixed this in my migration, adding:

        // update table structure in CakePHP
        TableRegistry::get('Chapters')->connection()->schemaCollection()->describe('chapters', [
            'forceRefresh' => true,
        ]);

But I think this should happen when the `save` method happens in the migration?

Thanks

**Comment by HavokInspiration** [comment] 2016-02-24 20:42
What version of the plugin are you using ?
Can you provide the second migrations, the one that alters the ``chapter_book_id`` column ?

I tested with the following migrations ``change`` methods (in two separate migrations) and it worked well :

```php
public function change()
{
    $table = $this->table('users');
    $table->addColumn('book_id', 'integer', [
        'default' => null,
        'limit' => 11,
        'null' => false,
    ]);
    $table->save();
}
```

```php
public function change()
{
    $table = $this->table('users');
    $table->changeColumn('book_id', 'integer', [
        'default' => null,
        'limit' => 5,
        'null' => true,
    ]);
    $table->save();
}
```

**Comment by steinkel** [comment] 2016-02-25 10:57
Thank you for taking a look @HavokInspiration 

Here's the code used the the next migration

    public function up()
    {
        $Chapters = TableRegistry::get('Chapters');
        $chapters = $Chapters->find();
        foreach ($chapters as $chapter) {
            $chapter['chapter_book_id'] = 1;
            $Chapters->save($chapter);
        }
    }

Versions used:
```
$ composer show -i
cakephp/bake                          1.1.3  
cakephp/cakephp                       3.1.7  
```

**Comment by HavokInspiration** [comment] 2016-02-25 11:20
Oh ok, I misunderstood the second part of what you did.
Thanks for the clarification.

What about the migrations plugin version ?
What you are experiencing should have been fixed with #165 ([released with 1.5.2](https://github.com/cakephp/migrations/releases/tag/1.5.2)) which is why I ask.

Depending on your answer, I'll take a look tonight if I get the time.

**Comment by steinkel** [comment] 2016-02-25 11:36
Sorry, the most important version was missing in my previous comment, anyway I did composer update to ensure we are using latest one:
```
$ composer show -i |grep cakephp
cakephp/bake                          1.2.1  
cakephp/cakephp                       3.2.3  
cakephp/chronos                       0.4.7  
cakephp/debug_kit                     3.2.6  
cakephp/migrations                    1.5.6  
cakephp/plugin-installer              0.0.12 
```
I could reproduce the issue in version 1.5.6 :( 
Adding the describe + forceRefresh call works

**Comment by HavokInspiration** [comment] 2016-02-25 11:59
Thanks for upgrading and testing, I'll try to reproduce and see if a fix can be found.
Out of curiosity, what db server are you using ? And what is your PHP version ?

**Comment by steinkel** [comment] 2016-02-25 12:06
```
$ php -v
PHP 5.6.11-1ubuntu3.1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
$ mysql --version
mysql  Ver 14.14 Distrib 5.6.28, for debian-linux-gnu (x86_64) using  EditLine wrapper
```
Thanks

**Comment by HavokInspiration** [comment] 2016-02-25 18:39
What class are your migrations extending ? Namespace included I mean.

If your migration is extending ``Phinx\Migration\AbstractMigration`` and not our own ``Migrations\AbstractMigration`` class, that would make sense.
The plugin's ``AbstractMigration`` class creates a custom instance of the phinx ``Table`` object (when you call ``$this->table()`` in a migration) which includes the ``TableRegistry`` clearing mechanism when doing a save operation.

If this is the problem, the doc probably needs a note about this.

**Comment by steinkel** [comment] 2016-02-27 00:52
hey @HavokInspiration, it's me again :)

I've used a clean cake setup and reproduced the issue.
Attached the migration files used
IMPORTANT: ensure you clear the orm_cache and the database. Then run migrations migrate and you'll get this output

```
:) ~/html/migrations-issue $ bin/cake migrations migrate

Welcome to CakePHP v3.2.3 Console
---------------------------------------------------------------
App : src
Path: /var/www/migrations-issue/src/
PHP : 5.6.11-1ubuntu3.1
---------------------------------------------------------------
using migration path /var/www/migrations-issue/config/Migrations
using seed path /var/www/migrations-issue/config/Seeds
using environment default
using adapter mysql
using database my_app

 == 20160226173848 Create: migrating
 == 20160226173848 Create: migrated 0.0221s

 == 20160226174013 Add: migrating
/config/Migrations/20160226174013_Add.php (line 20)
########## DEBUG ##########
[
	(int) 0 => 'id',
	(int) 1 => 'title',
	(int) 2 => 'description_id'
]
###########################
/config/Migrations/20160226174013_Add.php (line 26)
########## DEBUG ##########
[
	(int) 0 => 'id',
	(int) 1 => 'title',
	(int) 2 => 'description_id'
]
###########################
Now running describe and forcing refresh.../config/Migrations/20160226174013_Add.php (line 31)
########## DEBUG ##########
[
	(int) 0 => 'id',
	(int) 1 => 'title',
	(int) 2 => 'description_id',
	(int) 3 => 'another_description_id'
]
###########################
 == 20160226174013 Add: migrated 0.0781s

All Done. Took 0.1017s
```

NOTE: the 'another_description_id' field only appears after forcing refresh on describe.

[20160226174013_Add.php.zip](https://github.com/cakephp/migrations/files/149139/20160226174013_Add.php.zip)

Thanks!

**Comment by steinkel** [comment] 2016-02-27 00:56
Using `TableRegistry::clear()` does not fix the issue as I understand was the intention here https://github.com/cakephp/migrations/pull/165/files#diff-e6fb3ae86b6330590f6e6e6672d34753R83
Check line 28 > 
[20160226174013_Add.php.zip](https://github.com/cakephp/migrations/files/149143/20160226174013_Add.php.zip)

Thank you!

**Comment by HavokInspiration** [comment] 2016-02-29 07:48
Thanks for the file, I'll try to reproduce with it.

**Comment by HavokInspiration** [comment] 2016-02-29 12:15
I was able to reproduce with your file.
I'll try to find what is going on.

**Comment by HavokInspiration** [comment] 2016-02-29 12:33
Ok, I see. Apparently, it is because of table cached meta data.
If I get the time, I'll work on a fix tonight.

**Comment by steinkel** [comment] 2016-02-29 12:54
Thank you for checking this.
Would make sense to clear the orm_cache on TableRegistry::clear() calls? Or check if there are models associated with the modified table in TableRegistry and remove their keys in the orm_cache when $table->update() is called for a more performant solution...

**Comment by HavokInspiration** [comment] 2016-02-29 13:07
I was more thinking about disabling the metadata caching feature when using the plugin. This should cover all cases and be easier to implement.

**Comment by steinkel** [comment] 2016-02-29 13:21
Yes, that would work too.
We could be causing some surprises if the migration is applied to a production environment AND the deploy script is not running orm_cache clear by mistake.

**Comment by HavokInspiration** [comment] 2016-02-29 13:41
That is a valid concern.

However, in my opinion, deployment issues are out of the plugin's scope. But I might be the only one feeling like that so I'm open to comments.
We can still disable the cache mechanism (to fix the issue you reported) but also add a ``orm_cache clear`` shell dispatch once the migration command was executed (need to check if that would work though) to address this specific concern. But I feel that this is something the plugin should not be doing and that this the role of some other lib or script...
It might be valuable to add a note about this is the doc though.

**Comment by HavokInspiration** [comment] 2016-02-29 20:57
PR #201 submitted.

**Closed by HavokInspiration** 2016-02-29 20:57 UTC
Labels: Defect
