### ISSUE TITLE
Bake is now required?

### ISSUE THREAD

**Issue by swiffer** [cakephp/migrations#447] opened 2020-04-11 13:34 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.5
* Migrations plugin version: dev-4.x
* Bake plugin version (if relevant): 2.0.9
* Database server (MySQL, SQLite, Postgres): Postgres
* PHP Version: 7.4.4
* Platform / OS: -

### What you did
In composer.json

```json
    "require": {
        ....
        "cakephp/cakephp": "^4.0.1",
        "cakephp/migrations": "4.x-dev",
        ....
    },
    "require-dev": {
        "cakephp/bake": "^2.0.3",
        ....
    },
```

### Expected Behavior
application console commands should just execute fine when running in production (composer install --no-dev)

### Actual Behavior
migrations now includes some commands depending on Bake\Command\SimpleBakeCommand which is not available in production. Running any application console command now is giving an error.

**Comment by dereuromark** [comment] 2020-04-11 13:37
Duplicate of https://github.com/cakephp/migrations/issues/433

**Closed by dereuromark** 2020-04-11 13:37 UTC

**Comment by swiffer** [comment] 2020-04-11 13:40
Yes, sorry have seen it already.

**Comment by dereuromark** [comment] 2020-04-21 17:04
https://github.com/cakephp/migrations/pull/456 will fix this
