### ISSUE TITLE
create migrations updates from database like when init is used

### ISSUE THREAD

**Issue by rrd108** [cakephp/migrations#104] opened 2015-07-26 18:45 UTC
This is a question / feature request.

Normally when I change my database tables, I do it in MySQL Workbench database schema, and than synchronize it to my actual database.

It would be nice to have a migration command what creates the migration, based on the used ALTER / CREATE / DROP statements, or by a database sync.

**Comment by HavokInspiration** [comment] 2015-07-27 10:53
If I understand correctly, you want to be able to create a Migrations file out of a pool of SQL queries (ALTER already existing tables, CREATE new ones, DROP existing ones...) ?

**Comment by rrd108** [comment] 2015-07-27 10:59
@HavokInspiration Yes. After I created the initial, I would like to do something similar for changes.

**Comment by AD7six** [comment] 2015-07-27 11:07
I also would like to have this workflow.

Would mean:

 * Load/read (but do not run) all existing migrations/the last snapshot, to know according to existing migrations what the previous db-schema was
 * Take a snapshot of the current db schema
 * compare the two, and make a migration of the differences

**Comment by HavokInspiration** [comment] 2015-07-27 11:56
Ok, got it. You need to compare two schemas : the current which was updated using the tool of your choice and the old one that is made out of all the existing migrations.

But I have reservations on this. That means we need to exclude potential tables / columns / whatever that were added by plugins. Otherwise the baked "diff snapshot" will contain instructions that does not need to be there. Or plugins migrations needs to be taken into considerations as well and be excluded of the diff. 
It might get tricky really quickly.

If MySQL Workbench can give you SQL statements to execute, you currently can do it by executing the SQL queries from your migration file using the ``execute()`` method.
It's not ideal and very centric to your driver but it can give you what you need for the time being.

```php
public function up() 
{
    $this->execute('SQL QUERY');
}
```

**Comment by lorenzo** [comment] 2015-07-27 11:59
We should wait for this, or lobby to get it merged: https://github.com/robmorgan/phinx/pull/610

**Comment by AD7six** [comment] 2015-07-29 08:45
> If MySQL Workbench can give you SQL statements to execute

In my own projects I'm actually in favor of using sql always for migrations, unless x-db compatibility is something you actually need. Otherwise, you may find your schema has subtle (or not so subtle) differences to what you'd expect.

**Comment by HavokInspiration** [comment] 2015-07-29 10:48
Yeah I know. Having a bake output similar for each DB driver when updating the snapshot tests of the plugin is a real hassle.

**Comment by dereuromark** [comment] 2015-11-15 15:38
Is there any progress on this?
Similar to how other migration tools work, e.g. propel2, there are two commands usually:

    migrate to migrate the existing files
    diff to generate a diff from the current head of DB and files

So for us in Cake Migrations plugin

    create {name}: generate an empty file
    diff {name}: generate the current diff 
    migrate: migrate up

**Comment by ionas** [comment] 2015-11-15 16:30
```cake migrations diff``` would be very useful as you could start creating the base scheme for instance in SequelPro.app an then once you are happy create an initial schema by doing diff :+1:.

**Comment by dereuromark** [comment] 2015-11-15 16:35
Since this worked like this in cake2 migrations it cannot be too hard to make it work like this for cake3, can it?

@ionas You can always create an initial one using "cake bake migration_snapshot".
This is the trivial case.
More difficult is the diff when there are already existing migration files present.

**Comment by ionas** [comment] 2015-11-15 16:42
That would also be kind of good as you could use external tools to build schema upgrades and then generate schema upgrade files like that :+1: (still).

**Comment by dereuromark** [comment] 2015-11-15 17:47
One solution could be to add https://github.com/mmatuson/SchemaSync on top to generate at least raw SQL or sth for now, if spinx cannot help us here.

**Comment by HavokInspiration** [comment] 2015-11-16 11:04
I personally did not start working on this (nor did I really start thinking about it).

@dereuromark Might be tricky since the class responsible for generating the diff was removed in Cake3 (but that can be solved really quickly). The other biggest problem would be to parse migrations files / generate the new schema to compare against the current without running the migrations and to have something consistent between cake schema reflection tools and phinx one.
I originally had the idea to try working with events that would be added in the migration process to get the schema and not run them, but I never started working on this.
Might be a lead if someone wants to give it a try.

**Comment by dereuromark** [comment] 2015-11-16 11:39
Yeah, maybe the ORM itself should be able to provide this? As I said, the other ORMs come with that feature out of the box (propel and doctrine migration diff), and so should Cake3 ORM as well. Having it as this migration plugin addon would of course work, as well.
//cc @lorenzo

**Comment by lorenzo** [comment] 2015-11-16 23:27
I would rather donate that code to phinx instead of having it in cake

**Comment by dereuromark** [comment] 2015-11-16 23:38
Why? It's a huge selling point along with a few other features that people are looking for when searching for ORMs in the enterprise field, before choosing doctrine then etc because those are shipped with all that.

**Comment by lorenzo** [comment] 2015-11-17 09:07
Mainly because we don't offer the code for migrations, but phinx does. We would have no immediate use for it without first integrating it with another tool

**Comment by HavokInspiration** [comment] 2015-12-22 12:47
I may have had an idea for this.
There are still lots of dark areas but it seems to be working in my head.
I hope to start working on this this week or next week.

**Comment by dereuromark** [comment] 2015-12-22 13:47
@HavokInspiration Let me know if I can help out, you can contact me (on IRC or elsewhere).

**Comment by HavokInspiration** [comment] 2015-12-26 11:55
My idea is the following :

- The mechanism would be implemented using a new bake command that would work like baking a snapshot :
``bin/cake bake migration_diff MyAwesomeDiff``

- After each ``migrations migrate`` or ``migrations rollback`` calls, the Schema of the database should be dumped. By dumped I mean, each table should be reflected in its ``Cake\Database\Schema\Table`` object, everything stored in an array and serialized. That serialized array would then be saved in a file in the same place the migrations lies (this is not problem for phinx as it matches migrations filename based on a specific pattern). This way, we have a clear and accessible database structure when the last database changes were done. 
(For what it's worth, I managed to do that already, by extracting some code from the snapshot generation task).
Doing that particular operation will sidestep one of the biggest issue I found for this feature : we do not need to run migrations in some kind of "dry" mode before doing the diff.

- When a call to ``bin/cake bake migration_diff`` is called, there should be a check to see if the history of the migrations (the ``phinxlog``) is in sync with the migrations files, and if not, the command will not do anything (with a nice error message of course). For instance, if I have migrations A, B, C and D and only A, B and C were migrated, D should be migrated before doing the diff, otherwise, this will bring quite a lot of troubles.

- If everything is in sync, the diff command will start by reflecting the current database structure. The dump will the be opened, unserialized and a comparison can now me made between each Schema structure. This will be done through a new class (some kind of Schema object comparator).
We will need to compare and write a migration file with the following operations  :
    - Indexes deletion
    - Columns deletion
    - Tables deletion
    - Tables addition
    - Changes in columns metadata (length, type, etc.)

There is one thing I currently fail to see : how we can find out about columns name change. 

This is basically the ground for the idea. I was planning of figuring out some stuff while implementing it.

Any thoughts ?

**Comment by dereuromark** [comment] 2015-12-26 12:02
Nice! This is pretty much exactly how propel:diff (and propel:migrate as precondition to be in sync before trying to diff) works as well.
So this sounds very reasonable to me.

As for your issue: I don't think this is solvable by design, so we don't have to provide this functionality.
There will be a "remove fieldA, add fieldB" in the migration file you will have to manually adjust.
IF we want to support it, we could in theory either compare the two field schemas and if everything except matches with the just mentioned "table modification" we can assume this is a rename operation, but in that case we might have to confirm in interactive mode ("Possible rename detected: ... Confirm?", or we could provide a comment way of saying: This used to be fieldA.
I like the first option here though.

**Comment by HavokInspiration** [comment] 2016-01-04 21:19
I started working on this.

**Comment by dereuromark** [comment] 2016-01-10 14:36
Thats great news. Does it work out the way we planned it so far?

**Comment by HavokInspiration** [comment] 2016-01-11 12:55
So far so good.
I extracted some methods from the ``ConfigurationTrait`` and the snapshot bake class to two new Traits, created the new Diff bake class and added the check for synchronicity between the migrations files and the phinx log.

I however haven't had the change to work on this for days as I was busy with the seed command feature.

**Comment by HavokInspiration** [comment] 2016-01-27 11:53
Just a small update to say that I'm still working on this. It's taking time because it's quite a piece of development. I'm also adding stuff I hadn't thought about as I go. Tests also consumes a lot of time.

I should start on building the schemas diff tool soon.

**Comment by HavokInspiration** [comment] 2016-01-30 00:49
My first draft of the diff tool gives the ability to detect :

- constraints deletions : plain deletion and from unique to non-unique (in this case the constraint becomes an index in the ``Schema\Table`` object)
- constraints changes : I stumbled on this out of luck actually. I deleted a FK in my schema and created a new one which had the same name but not the same references
- constraints addition
- indexes deletions
- indexes changes (for instance if you changed the column an index is referring to without changing its name)
- indexes additions
- columns additions
- columns changes (change of type, of length, etc. Everything that is stored in the ``_columns`` property of a ``Schema\Table`` object)
- columns deletions
- tables additions
- tables deletions

Any more cases I did not think about ?

There is still the matter of column rename which could cause trouble (the current implementation I have will detect it as a "delete old column name" and "create new column name" resulting in data loss if there are data in the column to be deleted). 
I currently see two options :
- adding a big red blanking warning about this specific case before running the diff baking
- adding an option that will allow the dev to hint the columns that were renamed.

Something like : 
```
bin/cake bake migration_diff MyDiff --rename articles[name]:articles[title] users[login]:users[username]
```

The above example will tell that the column ``name`` from the ``articles`` table was renamed to title and that the column ``login`` from the table ``users`` was renamed to ``username``.
Any thoughts on this ?

I also suggest we do a beta-release of what will be 1.6 of the plugin with this new feature, so we can have some feedback before considering it stable.

**Comment by dereuromark** [comment] 2016-01-30 04:37
I'd be pragmatic and go with the warning. Should suffice for the first release.

**Comment by beporter** [comment] 2016-01-30 10:56
I'm inclined to agree with Mark. Even the old Cake 2 plugin wasn't able to detect column renames, so this is at least no worse that before. A warning that, "the possibility for data loss has been detected--please review added and deleted columns," will actually **improve** the situation compared to what we had. 

It seems like it might be possible (conceptually at least) to use some logic that compares all of the _other_ characteristics of any fields detected as "delete, add" to see if they might constitute a rename. The downside would be the prevalence of fields represented as common base types-- most string fields all end up as a generic and undifferentiated VARCHAR(255) (in MySQL dialect) for example. But, in a case where there is exactly one field being "deleted" and one being "added" and their attributes are otherwise identical, that seems like reasonable evidence to suggest the operation being a rename. In fact, it might even be preferable to default to assuming a rename in cases like this since there's less harm done to the data in performing the operation as a rename when a delete+add was intended versus performing a delete+add when a rename was intended. Obviously this is all just brainstorming for future consideration of course. 

I'm quite excited to try this out since this is a feature I sorely miss from Cake 2. Thanks for your efforts.

**Comment by dereuromark** [comment] 2016-01-30 11:00
Also: Dont forget that the big existing tools like propel migration still also cant handle these things. So it should be fine with such a base version for a while. we have lots of time to become the most advanced tool in the near or far future :)

**Comment by HavokInspiration** [comment] 2016-05-11 20:24
PR #217 has been opened to address this.

**Closed by HavokInspiration** 2016-05-11 20:24 UTC
Labels: enhancement
