### ISSUE TITLE
Undefined property: Migrations\Command\Dump::$connection

### ISSUE THREAD

**Issue by makallio85** [cakephp/migrations#239] opened 2016-06-09 08:48 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP 3.2.10
* Migrations 1.6.1
* Bake 1.2.4
* MariaDB 10.1.9
* PHP 7.0.0
* Windows 7 x64

### What you did
In this gist ( https://gist.github.com/makallio85/d3af39cd211d9255c3020c8e7fdbfd5f ), migrating causes InternalServerException

Migration file was created with bake tool with earlier version of migrations.

It seems that it is still working correctly with Migrations 1.5.7 but not with 1.6.1

**Comment by HavokInspiration** [comment] 2016-06-09 11:48
Thanks for the file and the output. I'll try to reproduce.

**Comment by HavokInspiration** [comment] 2016-06-09 21:07
I mimicked your setup (migrations from a plugin), while I did not encounter the same error, I got an error from the same line (I actually don't understand the error you are getting in the place you are getting it).

The error was because my plugin was not declared in the autoload-psr4 property of my composer file.
Is it the same for you ? Is your plugin not declared ?

I'll try to provide a fix to prevent the error from occurring but I just wanted to know.

**Comment by HavokInspiration** [comment] 2016-06-09 21:09
It somehow has some link to #232 by the way.

@makallio85 Do you have ``Table`` class in your plugin for those two tables ?

**Comment by HavokInspiration** [comment] 2016-06-09 21:16
OK, strike that one, I was running code on dev-master and not 1.6.1...
I'll study that with the good code base... Sorry.

**Comment by HavokInspiration** [comment] 2016-06-09 21:53
Ok I found a fix. I'll wait for #236 to be merged because I need something from it to properly fix this.
Thanks for the report !

**Comment by HavokInspiration** [comment] 2016-06-12 11:11
PR #241 opened

**Closed by HavokInspiration** 2016-06-12 11:11 UTC
Labels: bug
