### ISSUE TITLE
Abstract method not implemented in CakeAdapter breaking migration create

### ISSUE THREAD

**Issue by csga5000** [cakephp/migrations#271] opened 2016-11-03 19:06 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.7
* Migrations plugin version: 1.6.3
* Database server: MySQL
* PHP Version: 5.6.23
* Platform / OS: Ubuntu 14.04.5 LTS

### What you did
```
bin/cake migrations create ChangePrivateAccessToCompanyBased
```

### Expected Behavior
```
Welcome to CakePHP v3.3.7 Console
---------------------------------------------------------------
App : src
Path: /var/www/ca/dnt-api/src/
PHP : 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
---------------------------------------------------------------
using migration path /var/www/ca/dnt-api/config/Migrations
using seed path /var/www/ca/dnt-api/config/Seeds
using migration base class Phinx\Migration\AbstractMigration
using default template
created ./config/Migrations/20161103190022_change_private_access_to_company_based.php
```

### Actual Behavior
```
Welcome to CakePHP v3.3.7 Console
---------------------------------------------------------------
App : src
Path: /var/www/ca/dnt-api/src/
PHP : 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
---------------------------------------------------------------
using migration path /var/www/ca/dnt-api/config/Migrations
using seed path /var/www/ca/dnt-api/config/Seeds
PHP Fatal error:  Class Migrations\CakeAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Migrations\CakeAdapter::getVersionLog) in /var/www/ca/dnt-api/vendor/cakephp/migrations
/src/CakeAdapter.php on line 672
PHP Stack trace:
PHP   1. {main}() /var/www/ca/dnt-api/bin/cake.php:0
PHP   2. Cake\Console\ShellDispatcher::run() /var/www/ca/dnt-api/bin/cake.php:33
PHP   3. Cake\Console\ShellDispatcher->dispatch() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:128
PHP   4. Cake\Console\ShellDispatcher->_dispatch() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:182
PHP   5. Migrations\Shell\MigrationsShell->runCommand() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:227
PHP   6. Cake\Console\Shell->runCommand() /var/www/ca/dnt-api/vendor/cakephp/migrations/src/Shell/MigrationsShell.php:110
PHP   7. call_user_func_array:{/var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/Shell.php:466}() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/Shell.php:466
PHP   8. Migrations\Shell\MigrationsShell->main() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/Shell.php:466
PHP   9. Symfony\Component\Console\Application->run() /var/www/ca/dnt-api/vendor/cakephp/migrations/src/Shell/MigrationsShell.php:97
PHP  10. Symfony\Component\Console\Application->doRun() /var/www/ca/dnt-api/vendor/symfony/console/Application.php:118
PHP  11. Symfony\Component\Console\Application->doRunCommand() /var/www/ca/dnt-api/vendor/symfony/console/Application.php:187
PHP  12. Symfony\Component\Console\Command\Command->run() /var/www/ca/dnt-api/vendor/symfony/console/Application.php:820
PHP  13. Migrations\Command\Create->execute() /var/www/ca/dnt-api/vendor/symfony/console/Command/Command.php:256
PHP  14. Phinx\Console\Command\Create->execute() /var/www/ca/dnt-api/vendor/cakephp/migrations/src/ConfigurationTrait.php:177
PHP  15. Migrations\Command\Create->bootstrap() /var/www/ca/dnt-api/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:92
PHP  16. spl_autoload_call() /var/www/ca/dnt-api/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:231
PHP  17. Composer\Autoload\ClassLoader->loadClass() /var/www/ca/dnt-api/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:231
PHP  18. Composer\Autoload\includeFile() /var/www/ca/dnt-api/vendor/composer/ClassLoader.php:301

Fatal error: Class Migrations\CakeAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Migrations\CakeAdapter::getVersionLog) in /var/www/ca/dnt-api/vendor/cakephp/migrations/src/CakeAdapter.php on line 672

Call Stack:
    0.0008     233632   1. {main}() /var/www/ca/dnt-api/bin/cake.php:0
    0.3364    3814200   2. Cake\Console\ShellDispatcher::run() /var/www/ca/dnt-api/bin/cake.php:33
    0.4297    4565472   3. Cake\Console\ShellDispatcher->dispatch() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:128
    0.4297    4565664   4. Cake\Console\ShellDispatcher->_dispatch() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:182
    0.4347    4626800   5. Migrations\Shell\MigrationsShell->runCommand() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:227
    0.4347    4628080   6. Cake\Console\Shell->runCommand() /var/www/ca/dnt-api/vendor/cakephp/migrations/src/Shell/MigrationsShell.php:110
    0.4552    4804888   7. call_user_func_array:{/var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/Shell.php:466}() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/Shell.php:466
    0.4552    4805504   8. Migrations\Shell\MigrationsShell->main() /var/www/ca/dnt-api/vendor/cakephp/cakephp/src/Console/Shell.php:466
    0.5924    6477784   9. Symfony\Component\Console\Application->run() /var/www/ca/dnt-api/vendor/cakephp/migrations/src/Shell/MigrationsShell.php:97
    0.6289    6746040  10. Symfony\Component\Console\Application->doRun() /var/www/ca/dnt-api/vendor/symfony/console/Application.php:118
    0.6291    6747072  11. Symfony\Component\Console\Application->doRunCommand() /var/www/ca/dnt-api/vendor/symfony/console/Application.php:187
    0.6292    6747616  12. Symfony\Component\Console\Command\Command->run() /var/www/ca/dnt-api/vendor/symfony/console/Application.php:820
    0.6302    6752056  13. Migrations\Command\Create->execute() /var/www/ca/dnt-api/vendor/symfony/console/Command/Command.php:256
    0.6304    6754152  14. Phinx\Console\Command\Create->execute() /var/www/ca/dnt-api/vendor/cakephp/migrations/src/ConfigurationTrait.php:177
    0.6304    6754376  15. Migrations\Command\Create->bootstrap() /var/www/ca/dnt-api/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:92
    0.7229    7980944  16. spl_autoload_call() /var/www/ca/dnt-api/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:231
    0.7229    7980984  17. Composer\Autoload\ClassLoader->loadClass() /var/www/ca/dnt-api/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:231
    0.7236    7981128  18. Composer\Autoload\includeFile() /var/www/ca/dnt-api/vendor/composer/ClassLoader.php:301
```

Also note:
I fixed this error and it seemed to work fine by adding:
```
public function getVersionLog() {}
```
To cakephp\migrations\src\CakeAdapter.php

**Comment by HavokInspiration** [comment] 2017-01-12 20:56
Hi @csga5000.

I can not reproduce the issue.
This method was added to the adapter with commit https://github.com/cakephp/migrations/commit/aa9ec2a8fdf208c6677a938eb6c9ccb08f75cc6d and shipped with version `1.5.8`.

Are you sure you are using version 1.6.3 as you specified in your issue ?

**Comment by csga5000** [comment] 2017-01-17 22:46
Here's the contents of my composer lock file:

```
        {
            "name": "cakephp/migrations",
            "version": "1.6.3",
            "source": {
                "type": "git",
                "url": "https://github.com/cakephp/migrations.git",
                "reference": "b683daebb6d0f0ea41546b14f8a9ea591cebedfd"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/cakephp/migrations/zipball/b683daebb6d0f0ea41546b14f8a9ea591cebedfd",
                "reference": "b683daebb6d0f0ea41546b14f8a9ea591cebedfd",
                "shasum": ""
            },
            "require": {
                "cakephp/cakephp": "~3.1",
                "php": ">=5.4",
                "robmorgan/phinx": "0.5.3"
            },
            "require-dev": {
                "cakephp/bake": "@stable",
                "phpunit/phpunit": "*"
            },
            "suggest": {
                "cakephp/bake": "Required if you want to generate migrations."
            },
            "type": "cakephp-plugin",
            "autoload": {
                "psr-4": {
                    "Migrations\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "CakePHP Community",
                    "homepage": "https://github.com/cakephp/migrations/graphs/contributors"
                }
            ],
            "description": "Database Migration plugin for CakePHP 3.0 based on Phinx",
            "homepage": "https://github.com/cakephp/migrations",
            "keywords": [
                "cakephp",
                "migrations"
            ],
            "time": "2016-06-23 17:18:29"
        }
```

I don't see any way to verify the version from the vendor/cakephp/migrations directory.

**Comment by HavokInspiration** [comment] 2017-01-18 07:40
That is very weird. If I check out the 1.6.3 tag repo, [the `getVersionLog` is implemented in `CakeAdapter`](https://github.com/cakephp/migrations/blob/1.6.3/src/CakeAdapter.php#L84-L92).

I'll try to run some tests by pinning to migrations 1.6.3.

In the meantime, can you try upgrading the versions of the plugin you are using with a `composer update` and try again ?

**Comment by HavokInspiration** [comment] 2017-01-19 21:26
I tried the `migrations create` command with migrations plugin v1.6.3 and the create executes without any error. I have doubts that you are really running the said version of the plugin, since the tagged version on the repo contains the line that seems to be missing in your version.

Can you try providing me the output of a `composer show -i | grep "migrations"` ?
Have you tried doing a `composer update` ?

**Comment by csga5000** [comment] 2017-01-20 00:56
It's this.

But if I'm the only person experiencing this issue, I'm cool calling it a fluke, I got it to work (by adding that function or whatever).  And updating would probably fix it anyway aside from me hacking it fixed.
```
> composer show -i | grep "migrations"
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
cakephp/migrations                    1.6.3              Database Migration plugin for CakePHP 3.0 based on Phinx
robmorgan/phinx                       v0.5.3             Phinx makes it ridiculously easy to manage the database migrations for your PHP app.
```

**Comment by HavokInspiration** [comment] 2017-01-21 22:55
Closing as there are no reasons for this to happen : version 1.6.3 of the plugin includes everything necessary to prevent the error reported.
@csga5000 If you ever find a way to reproduce this, do not hesitate to open a new ticket.

**Closed by HavokInspiration** 2017-01-21 22:55 UTC
Labels: bug, On hold
