### ISSUE TITLE
Migration Seed for Postgres driver was get PDO Error (There is no active transaction for seed data)

### ISSUE THREAD

**Issue by dremi** [cakephp/migrations#83] opened 2015-05-11 08:50 UTC
I'm trying to create seed data from CakePHP 3 migration file, with Postgres as database driver. But i have got error message under console after run:

```php
bin/cake migrations migrate
```

![PDOException: There is no active transaction](http://i846.photobucket.com/albums/ab22/dremiINFO/Screenshot%20from%202015%2005%2011%2015%2002%2043.png)

Here are my code:

```php
<?php
use Phinx\Migration\AbstractMigration;
use Cake\ORM\TableRegistry;
use Cake\Utility\Security;

class CreateSeedUsers extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
        $modelName = 'Users';
        
        $data = [
            [
                'username' => 'admin', 
                'email' => 'admin@demo.com', 
                'password' => Security::hash('123', 'sha1', true)
            ], 
            [
                'username' => 'seller', 
                'email' => 'seller@demo.com', 
                'password' => Security::hash('123', 'sha1', true)
            ], 
            [
                'username' => 'member', 
                'email' => 'member@demo.com', 
                'password' => Security::hash('123', 'sha1', true)
            ]
        ];
        
        $table = TableRegistry::get($modelName);
        $entities = $table->newEntities($data);
        
        // In a controller.
        foreach ($entities as $entity) {
            // Save entity
            $table->save($entity);
        }   
    }

    /**
     * Migrate Down.
     */
    public function down()
    {
        if ($this->query("TRUNCATE users")) {
            echo " > Table has been initialized\n\n";
        } 
        else 
        {
            echo " > Warning, table failed to initialized!!!\n\n";
        }
    }
}

```

If i use mysql as database driver, its working good.

Someone please help me. Thank you.

**Comment by HavokInspiration** [comment] 2015-05-27 17:31
As far as I'm concerned, I tried your code and had the same problem.
Out of curiosity, I executed this (the ``up()`` method) in the app just at the end of the bootstrap.php file and it worked well.

So I dug further and I was able to make the migration work by passing the ``atomic`` option of the ``save()`` method to ``false`` :

```php
$table->save($entity, ['atomic' => false]);
```

This turns transaction off and avoid the exception to be raised, so it should work (I tested this on Cake 3.0.5).

As for why it is working when executing while migrating and not while executing the app itself, I have no idea. I'll try to investigate this but it might take some times since I don't really that part of the framework.

**Comment by HavokInspiration** [comment] 2015-05-27 18:53
Apparently, Phinx starts a transaction by itself when migrating [(see source)](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Migration/Manager/Environment.php#L95-L97).

Maybe that's what causing a problem here.
I'll take a deeper look when I get the chance. Maybe there is something that can be done to prevent this. But I'm sceptical since it works well with MySQL...

Meanwhile, the ``atomic`` trick from my previous comment should work.

**Comment by HavokInspiration** [comment] 2015-06-01 19:58
There is definitely something going on here.
I don't quite understand it though.

If I define two connections ``default`` and ``postgres`` with the same credentials for the Postgres driver and do :

``bin/cake migrations migrate``

I get the exception.
But if I do 

``bin/cake migrations migrate -c postgres``

The exception is not raise and the migration is correctly migrated.
And finally if I do

``bin/cake migrations migrate -c default``

The exception is raised.
Maybe it is related to how Connection object are dealt with / constructed.

I'll dig deeper but if someone has an idea...

**Comment by HavokInspiration** [comment] 2015-06-01 20:47
I think I figured it out.
After some poking around, I found out that phinx starts transactions with raw SQL statement (like ``BEGIN`` or ``START TRANSACTION``).
However, it does not use the ``PDO::beginTransaction()`` method which is causing the problem here I think.
If, I change [this method](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Db/Adapter/PostgresAdapter.php#L100-L103) to

```php
public function beginTransaction()
{
    $this->execute('BEGIN');
    $this->getConnection()->beginTransaction();
}
```

Otherwise, it seems to create some kind of conflicts.
I think the problem is within phinx and nothing can really be done in this plugin (we could maybe try and build our own adapters but that is not really viable in the long term in my opinion).

**Comment by josegonzalez** [comment] 2015-06-01 21:18
So make a pr for it in sphinx?

**Comment by HavokInspiration** [comment] 2015-06-02 06:43
@josegonzalez That is the plan. I just have to do extensive testing beforehand (and find time to do it).

**Comment by dremi** [comment] 2015-06-05 03:45
Hi HavokInspiration,

I have try to use 

```php
$table->save($entity, ['atomic' => false]);
```

![Bin Cake Console Migrations migrate](http://i846.photobucket.com/albums/ab22/dremiINFO/Screenshot%20from%202015%2006%2005%2010%2037%2051.png)

![migrate seed result](http://i846.photobucket.com/albums/ab22/dremiINFO/Screenshot%20from%202015%2006%2005%2010%2037%2055.png)

So far, its working now. I hope i can get the latest fix updated on newest release.
Thanks for all.

**Comment by HavokInspiration** [comment] 2015-06-05 07:26
@dremi I started working on a fix for phinx yesterday night. I still need to do some tests. 
Hopefully I'll be able to submit it tonight.

**Comment by dremi** [comment] 2015-06-05 08:42
Hi HavokInspiration,

Thanks for your update.

**Comment by HavokInspiration** [comment] 2015-06-05 21:13
I gave this another round and I think there is nothing to actually fix.
Here's what is really going on :

```
1. Migration starts
2. Phinx starts a transaction
3. CakePHP ORM starts saving the given rows.
   By default, at the end of a save, it commits the transaction created by Phinx
4. Phinx commits the transaction... but can not since it was already commited
```

And the problem is the other way around if the code base from phinx is left as is.
I have the same problem if phinx deals with transaction with ``PDO`` methods rather than with raw queries with MySQL this time. Except that data is saved in the database and the migration failed right after, but the data is still there)

So I'm back to square one. 
The only real way to have something working in all cases would be to disable transactions on Cake when running in Migrations. Is there a way to do it other than passing ``atomic`` to ``false``.

**Comment by lorenzo** [comment] 2015-06-05 21:25
I can take a look at this @HavokInspiration

**Comment by markstory** [comment] 2015-06-06 00:49
Closing as there is a pull request now.

**Closed by markstory** 2015-06-06 00:49 UTC
Labels: bug
