### ISSUE TITLE
bake migration "create" throws error on 1.6.0

### ISSUE THREAD

**Issue by Spriz** [cakephp/migrations#230] opened 2016-05-23 17:04 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.2.9
* Migrations plugin version: 1.6.0
* Bake plugin version (if relevant): 1.2.4
* Database server (MySQL, SQLite, Postgres): mysql  Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* PHP Version: PHP 5.6.21-9+donate.sury.org~trusty+1 (cli)
* Platform / OS: Ubuntu 14.04.3 LTS

### What you did
`bin/cake bake migration CreateDistributors id:uuid:primary name:string created modified deleted:datetime`

### Expected Behaviour
That a new migration file is baked

### Actual Behaviour
Throws me an error: `Error: Too many arguments.`

### Gist with output: 
https://gist.github.com/Spriz/5455ab49b42ca78acdde842c810b2935

### Fix
Downgrade to migrations 1.5.8

**Comment by HavokInspiration** [comment] 2016-05-23 20:12
Duplicate of #226 and #228 
PR #227 will fix it. A release will be made shortly after that.
Sorry for the inconvenience.

**Closed by HavokInspiration** 2016-05-23 20:12 UTC

**Comment by HavokInspiration** [comment] 2016-05-23 20:37
Migrations 1.6.1 released. It should fix the problem.

**Comment by Spriz** [comment] 2016-05-23 20:38
Sorry about the duplicate :-)  GJ
