### ISSUE TITLE
Foreign keys in baked migrations

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/migrations#84] opened 2015-05-13 09:29 UTC
When baking a migration for a table containing foreign keys, the foreign keys don't end up in the migrations file. Seems like I'll have to add them manually for now, this would be a really good feature to have in `bake`.

**Comment by HavokInspiration** [comment] 2015-05-13 09:43
Related to #80 
I started working on this yesterday night and I have something working for single column FK. 
It needs more work to support multiple columns and it also needs tests.

**Comment by markstory** [comment] 2015-05-13 19:56
Dupe of #80

**Closed by markstory** 2015-05-13 19:56 UTC

**Comment by HendrysTobar** [comment] 2020-02-02 18:12
This request is closed. Was the feature added? if so, how do you add FK with bake migrations?

**Comment by garas** [comment] 2020-02-02 20:04
Both `bin/cake bake migration_snapshot` and `bin/cake bake migration_diff` generates migration file with code to add/drop foreign keys.

If it doesn't, please open new issue with information of your system and DB schema.
