### ISSUE TITLE
RFC: Migration Generation via Schema Comparison

### ISSUE THREAD

**Issue by JD-Robbs** [cakephp/migrations#131] opened 2015-10-06 15:26 UTC
CakePHP 2.5 (edit: read "2.x") and its migration plugin had the nifty feature of automatically generating "incremental" migrations based on schema comparisons - saving one from manually having write-out the migrations.

For that purpose, CakePHP used this nifty method (after getting confirmation via the CLI): https://github.com/cakephp/cakephp/blob/2.5/lib/Cake/Model/CakeSchema.php#L451

I wonder if something similar was/is planned for the new Migrations plugin?

**Comment by HavokInspiration** [comment] 2015-10-06 17:09
Seems like a duplicate of #104

**Closed by HavokInspiration** 2015-10-06 17:09 UTC

**Comment by JD-Robbs** [comment] 2015-10-06 17:37
Whoopsie - I missed that. My apologies. :smiley:
