### ISSUE TITLE
Feature or question: Running migrations via php (not a shell)?

### ISSUE THREAD

**Issue by burzum** [cakephp/migrations#37] opened 2014-12-15 14:53 UTC
Is it already possible to simply run existing migrations via php?

I'm working on an installer like shell and would like to run migrations from there, I have something like 

```php
$migrations->migrate();
$migrations->migrate('SomePlugin');
```

in mind. Without the need to lookup and load the migration files manually.

**Comment by HavokInspiration** [comment] 2015-06-15 11:05
If I understand this correctly, you want to be able to run migrations from a "classic" app ?
From a Controller for instance ?

Is this issue linked to #61 ?

**Comment by burzum** [comment] 2015-06-15 11:07
@HavokInspiration correct.

**Comment by HavokInspiration** [comment] 2015-06-15 19:22
Ok. I'll give it a try to see if that's possible.

**Comment by HavokInspiration** [comment] 2015-06-21 18:41
I gave this a try and it seems to be possible. 

I was able to run the "status" command in a controller.
However, the output is not really nice as it is strictly what the console would return :

```
/src/Controller/MigrationsController.php (line 27)

'using migration path /home/yves/PhpStormProjects/cakephp-app/config/Migrations
using environment default
using format json

 Status  Migration ID    Migration Name 
-----------------------------------------
   down  20150531090528  CreateSeedUsers

[{"migration_status":"down","migration_id":"20150531090528","migration_name":"CreateSeedUsers"}]
```

**Comment by burzum** [comment] 2015-06-23 11:30
@HavokInspiration I think this is something that should be fixed in Phinx because AFAIR this is returned from Phinx and not the CakePHP plugin. Also see this issue https://github.com/robmorgan/phinx/issues/534

**Comment by HavokInspiration** [comment] 2015-06-23 11:50
Yes, that is what Phinx returns when you call the ``status`` command. The CakePHP plugin does not return anything expect for the MarkMigrated command since we implemented it.

In my POC, instead of using the default console output, I use the ``BufferedOutput`` which, as its name states, buffers the output. I returned it as well as the shell app exit code (which is not shown in my debug in my previous post).

Parsing the text output could be a solution but we are going to need one parser per command. The idea did cross my mind, but I don't really like it. I have a feeling that this might over-complicate things.

I know this would be less than ideal, but my initial plan was to give the ability to run migrations inside apps and return the full output and the exit code, and see how people reacted.

**Comment by burzum** [comment] 2015-06-23 12:13
I agree with the overall goal with you but not with the implementation.

> I know this would be less than ideal, but my initial plan was to give the ability to run migrations inside apps and return the full output and the exit code, and see how people reacted.

But I wouldn't try to work with the exit code of a shell inside an app. That's why I would prefer meaningful return values or exceptions from the methods.

```php
$migrations = new Migrations();
$migrations->migrate(); // return bool
$migrations->rollback(); // return bool
$migrations->status(); // return an array
$migrations->getLastError () // Gets the last error
// ...
```

Or instead of the getLastError throw an exception and return always true (or nothing at all).

The same code should be used within an app and the shell IMHO, the shell will just transform the return values into meaningful (text) shell output and use it to determine the return code as well.

**Comment by lorenzo** [comment] 2015-06-23 17:16
@HavokInspiration What about using the json output for generating whatever type for message at the end?

**Comment by HavokInspiration** [comment] 2015-06-23 20:00
@lorenzo The json output for the status command is what you can preview from one of my previous post. It actually adds a json output after displaying the normal output (yeah, I don't really understand why). [See ref in phinx source](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Migration/Manager.php#L76-L130)
And I think that only the status command has a json output.

@burzum Yeah, I get what you want. The current state of phinx does not allow that, as you pointed out in the issue you linked. If we want that, we have two solutions :

* we patch phinx
* we create our own manager to rewrite what we don't like (the same way @lorenzo created the ``CakeAdapter``).

As for the implementation I'm talking about, there is little choice.
phinx is based on the Symfony Console, which has a "Shell app" logic. To run an app, you need two arguments : an Input and an Output. My solution was to simply use the good types of Input (ArrayInput) and Output (BufferedOutput) within a custom class. This class would have had a method per phinx command to prepare the Input argument with Shell parameters and options, so this can be done :

```php
$out = $this->migrations()->status([
      'format' => 'json',
      'connection' => 'default',
      'source' => false,
      'plugin' => 'DebugKit'
]);
```

The array argument is the options available for the status command. 

The app is launched this way :

```php
        $app = new MigrationsDispatcher(PHINX_VERSION);
        $input = new ArrayInput($options); // $option is the array of parameter formated as needed for the app to properly run + the command name
        $output = new BufferedOutput();

        $app->setAutoExit(false);
        $code = $app->run($input, $output);
```

To get what the console output, you run a ``$output->fetch()``. The ``run()`` method returns the console exit code.

But if you want to get something else (a bool, an array, or whatever), you need to rewrite the way phinx works because it was designed as a console tool : it does not return anything, it just outputs a response.

**Comment by HavokInspiration** [comment] 2015-06-30 14:46
I worked on this a bit more and I was able to produce something better.

I introduced a ``CakeManager`` that aims to change the behavior of this part of phinx. 
Our manager will now only be responsible for returning necessary values.
I delegated the output to the ``Command`` classes.

On top of that, I provide a ``Migrations`` class that gives the ability to run phinx command from within an app (by kind of "mocking" everything the Manager needs to run his methods).

Right now I only have something working for the ``status`` command (it was the easiest one).
I hope I can do something for the ``rollback`` and the ``migrate`` commands.

(Oh, and I have a feeling that adding unit tests to this is going to be so much fun...).

**Comment by burzum** [comment] 2015-07-06 08:22
@HavokInspiration any progress on this we could review / test? :)

**Comment by HavokInspiration** [comment] 2015-07-06 10:50
I started writing tests this week-end, so I'm correcting bugs and adding enhancements.
Nothing stable enough to show right now though.
But I'm working on it.

**Comment by HavokInspiration** [comment] 2015-07-30 20:12
Closing as #97 is open.

**Closed by HavokInspiration** 2015-07-30 20:12 UTC
Labels: enhancement, question
