### ISSUE TITLE
Cache issues?

### ISSUE THREAD

**Issue by adayth** [cakephp/migrations#157] opened 2015-11-23 13:15 UTC
I usually have issues with caching when I'm playing with migrations.

Consider this piece of code:
```php
$RoomPricesTable = \Cake\ORM\TableRegistry::get('MyRoomPricesTable', ['table' => 'room_prices']);
$roomPrices = $RoomPricesTable->find()->all()->toArray();

$this->table('room_prices')
            ->changeColumn('price', 'text', [
                'default' => '',
                'limit' => null,
                'null' => false,
            ])
            ->renameColumn('price', 'prices')
            ->update();

$RoomPricesTable = \Cake\ORM\TableRegistry::get('MySecondRoomPricesTable', ['table' => 'room_prices']);
// Code to migrate $roomPrices->price decimal values into a JSON ARRAY in $roomPrices->prices
```

I detected that usually Cake doesn't detect column changes after calling $table->update(), so I tried to force it instantiating a new table. Sometimes it works, sometimes it doesn't. I even delete all my tables, run all migrations and have DB errors of missing columns with debug enabled while trying to open my application in a navigator

What could be the cause? 
Is Cake related or could be a configuration issue?

**Comment by lorenzo** [comment] 2015-11-23 13:25
I think it could make sense to force disable caching in the migrations shell

**Comment by adayth** [comment] 2015-11-23 14:27
We could also study forcing an ORM cache reset after a migration.

**Comment by lorenzo** [comment] 2015-11-23 14:45
@adayth I usually call that manually using the orm_cache shell

**Comment by HavokInspiration** [comment] 2015-11-29 11:54
I suspect the issue is coming from the Schema stored in Table objects (in the  ̀̀ ̀_schema`̀` property).
The only way I found to make the example @adayth gave was to add a ``TableRegistry::clear()`` after the ``update()`` call + creating a new instance of the Table object.
Other than that, I always get an error because if the same instance is used, the Schema is not reloaded.

I don't think there is another way to prevent the error from happening. But I might be wrong.
@lorenzo : What was your idea of disabling cache ?

**Comment by lorenzo** [comment] 2015-11-29 12:29
@HavokInspiration You are right, the only solution would be to trash clear the registry on each update.

**Comment by HavokInspiration** [comment] 2015-12-02 18:16
Closing as pull request #165 is up.

**Closed by HavokInspiration** 2015-12-02 18:16 UTC
Labels: Defect
