### ISSUE TITLE
New Version of Phinx

### ISSUE THREAD

**Issue by MatLomax** [cakephp/migrations#160] opened 2015-11-30 18:25 UTC
Since Phinx updated to v0.5.0 migrations are now breaking with the following error message: 

```
PHP Fatal error:  Declaration of Migrations\CakeAdapter::insert() must be compatible with Phinx\Db\Adapter\AdapterInterface::insert(Phinx\Db\Table $table, $row) in /vagrant/vendor/cakephp/migrations/src/CakeAdapter.php on line 28
```
According to the phinx changelog, they've changed the method signature causing this error.

For now, have resolved by manually targeting phinx v0.4.6, rolling migrations back to v1.3.

As a quick fix, I suggest targeting phinx 0.4 instead of dev-master until you have implemented these changes.

**Comment by dereuromark** [comment] 2015-11-30 18:55
Duplicate of https://github.com/cakephp/migrations/pull/159

**Closed by dereuromark** 2015-11-30 18:55 UTC

**Comment by robmorgan** [comment] 2015-11-30 19:28
@MatLomax I sent an upstream patch. The guys will merge it soon.
