### ISSUE TITLE
bake migration bug

### ISSUE THREAD

**Issue by charliee22** [cakephp/migrations#228] opened 2016-05-23 08:32 UTC
This is a (multiple allowed):
* [x] bug (not sure)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Migrations plugin version: ~1.0
* Bake plugin version (if relevant): ~1.1
* Database server (MySQL, SQLite, Postgres): SQLite
* PHP Version: PHP 5.5.31 
* Platform / OS: OS X EL Capitan

### What you did
I did this:
`bin/cake bake migration CreateProducts name:string description:text created modified`

### Expected Behavior
Expected the generated file

### Actual Behavior
output: `Error: Too many arguments.`

**Comment by HavokInspiration** [comment] 2016-05-23 09:07
Duplicate of #226
PR #227 was opened to fix it. It should be merged shortly and a new release will be made after that.
Sorry for the inconvenience.

**Closed by HavokInspiration** 2016-05-23 09:07 UTC

**Comment by HavokInspiration** [comment] 2016-05-23 20:37
Migrations 1.6.1 released. It should fix the problem.
